# Generated by Django 3.2.17 on 2023-02-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mom_schedule_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mom_task',
            name='description',
            field=models.CharField(default='test', max_length=500),
        ),
        migrations.AlterField(
            model_name='mom_task',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
