# Generated by Django 3.2.17 on 2023-02-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mom_schedule_app', '0002_auto_20230210_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mom_task',
            name='description',
        ),
        migrations.AddField(
            model_name='mom_task',
            name='test',
            field=models.BooleanField(default=False),
        ),
    ]
