# Generated by Django 3.2.17 on 2023-02-10 13:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mom_schedule_app', '0003_auto_20230210_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mom_task',
            name='test',
        ),
        migrations.AddField(
            model_name='mom_task',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
