# Generated by Django 3.2.17 on 2023-02-11 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mom_schedule_app', '0005_mom_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mom_user',
            name='user',
        ),
        migrations.AddField(
            model_name='mom_task',
            name='task_owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
