# Generated by Django 3.2.17 on 2023-02-11 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mom_schedule_app', '0006_auto_20230211_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mom_task',
            name='task_owner',
        ),
        migrations.AddField(
            model_name='mom_user',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mom_user',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
