# Generated by Django 3.2.17 on 2023-02-11 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mom_schedule_app', '0007_auto_20230211_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='mom_task',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='momtask', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Mom_user',
        ),
    ]
