# Generated by Django 3.2.17 on 2023-02-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mom_schedule_app', '0008_auto_20230211_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mom_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('topic', models.CharField(max_length=50)),
                ('your_message', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='mom_task',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
