# Generated by Django 3.2.17 on 2023-02-18 19:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mom_schedule_app', '0009_auto_20230216_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='mom_task',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mom_task',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
