# Generated by Django 3.2.17 on 2023-02-22 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mom_schedule_app', '0011_task_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='mom_task',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mom_schedule_app.task_category'),
        ),
    ]
