# Generated by Django 3.2.17 on 2023-02-25 18:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mom_schedule_app', '0013_auto_20230224_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='mom_task',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mom_task',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
