# Generated by Django 3.2.17 on 2023-02-28 13:20

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mom_schedule_app', '0015_auto_20230226_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_category',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='mom_task',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mom_schedule_app.task_category'),
        ),
    ]
