# Generated by Django 3.2.17 on 2023-03-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mom_schedule_app', '0016_auto_20230228_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mom_task',
            name='end_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='mom_task',
            name='start_time',
            field=models.DateField(),
        ),
    ]
